/**
 * AUTO-GENERATED by Supabase CLI
 * Run: npx supabase gen types typescript --project-id ijbbhtljxqnjboyhrjqw > lib/database.types.ts
 *
 * For now, this is a manual stub. Replace with auto-generated version after setup.
 */

export interface Database {
  public: {
    Tables: {
      businesses: {
        Row: {
          id: string;
          name: string;
          type: string;
          address: string;
          location: { lat: number; lng: number };
          operator_name: string;
          staffing_state: string;
          phone: string | null;
          password: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['businesses']['Row'], 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['businesses']['Insert']>;
      };
      candidates: {
        Row: {
          id: string;
          business_id: string;
          name: string;
          phone: string | null;
          initials: string;
          avatar_color: string;
          neighborhood: string;
          location: { lat: number; lng: number };
          has_car: boolean;
          willing_range_km: number | null;
          availability: any;
          roles: string[];
          experience: any;
          skills: string[];
          languages: string[];
          has_work_permit: boolean;
          age: number | null;
          expected_wage_nis: number | null;
          signals: any;
          consent_source: string;
          needs_supplies_fit: string[] | null;
          schedule_tolerance: string | null;
          interview_scores: any | null;
          dna_source: string | null;
          dna_confidence: number | null;
          added_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['candidates']['Row'], 'created_at' | 'updated_at' | 'added_at'>;
        Update: Partial<Database['public']['Tables']['candidates']['Insert']>;
      };
      employees: {
        Row: {
          id: string;
          business_id: string;
          candidate_id: string;
          hired_at: string;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['employees']['Row'], 'created_at' | 'updated_at' | 'hired_at'>;
        Update: Partial<Database['public']['Tables']['employees']['Insert']>;
      };
      jobs: {
        Row: {
          id: string;
          business_id: string;
          role: string;
          location_address: string | null;
          location: { lat: number; lng: number };
          shifts: string[];
          start_date: string | null;
          requirements: string | null;
          wage_nis: number | null;
          filters: any;
          weights: any;
          must_haves: string[];
          flow: string;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['jobs']['Row'], 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['jobs']['Insert']>;
      };
      invites: {
        Row: {
          id: string;
          job_id: string;
          candidate_id: string;
          status: string;
          sent_at: string;
          responded_at: string | null;
          wa_message: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['invites']['Row'], 'created_at' | 'updated_at' | 'sent_at'>;
        Update: Partial<Database['public']['Tables']['invites']['Insert']>;
      };
      qr_scans: {
        Row: {
          id: string;
          business_id: string;
          candidate_id: string;
          scanned_at: string;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['qr_scans']['Row'], 'created_at' | 'scanned_at'>;
        Update: Partial<Database['public']['Tables']['qr_scans']['Insert']>;
      };
      wa_interview_results: {
        Row: {
          id: string;
          candidate_id: string;
          business_id: string;
          phases_completed: number;
          answers: any;
          dna_score: number | null;
          dna_confidence: number | null;
          retention_fit: number | null;
          performance: number | null;
          churn_risk: string | null;
          completed_at: string;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['wa_interview_results']['Row'], 'created_at' | 'completed_at'>;
        Update: Partial<Database['public']['Tables']['wa_interview_results']['Insert']>;
      };
      wa_sessions: {
        Row: {
          phone: string;
          candidate_id: string | null;
          business_id: string;
          business_name: string | null;
          candidate_name: string | null;
          step: string;
          answers: any;
          phases_completed: number;
          started_at: string;
          last_activity_at: string;
          form_completion_sec: number | null;
          first_reply_latency_sec: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['wa_sessions']['Row'], 'created_at' | 'updated_at' | 'started_at' | 'last_activity_at'>;
        Update: Partial<Database['public']['Tables']['wa_sessions']['Insert']>;
      };
      employee_requests: {
        Row: {
          id: string;
          business_id: string;
          employee_id: string;
          type: string;
          status: string;
          details: string | null;
          submitted_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['employee_requests']['Row'], 'created_at' | 'updated_at' | 'submitted_at'>;
        Update: Partial<Database['public']['Tables']['employee_requests']['Insert']>;
      };
      candidate_preferences: {
        Row: {
          id: string;
          business_id: string;
          candidate_id: string;
          saved: boolean;
          dismissed: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['candidate_preferences']['Row'], 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['candidate_preferences']['Insert']>;
      };
    };
    Views: {};
    Functions: {};
    Enums: {};
  };
}
