/**
 * AUTO-GENERATED by Supabase CLI
 * Run: npx supabase gen types typescript --project-id ijbbhtljxqnjboyhrjqw > lib/database.types.ts
 *
 * For now, this is a manual stub. Replace with auto-generated version after setup.
 */

export interface Database {
  public: {
    Tables: {
      clinics: {
        Row: {
          id: string;
          name: string;
          type: string;
          address: string;
          operator_name: string;
          phone: string | null;
          email: string | null;
          plan: string;
          trial_ends_at: string | null;
          wa_phone_number_id: string | null;
          wa_access_token_encrypted: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['clinics']['Row'], 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['clinics']['Insert']>;
      };
      memberships: {
        Row: {
          id: string;
          user_id: string;
          clinic_id: string;
          role: string;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['memberships']['Row'], 'created_at'>;
        Update: Partial<Database['public']['Tables']['memberships']['Insert']>;
      };
      patients: {
        Row: {
          id: string;
          clinic_id: string;
          name: string;
          phone: string;
          initials: string | null;
          avatar_color: string | null;
          age: number | null;
          gender: string | null;
          first_visit: string;
          last_visit: string;
          medical_notes: string | null;
          consent: boolean;
          opted_out: boolean;
          added_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['patients']['Row'], 'created_at' | 'updated_at' | 'added_at'>;
        Update: Partial<Database['public']['Tables']['patients']['Insert']>;
      };
      treatments: {
        Row: {
          id: string;
          clinic_id: string;
          patient_id: string;
          date: string;
          category: string;
          name: string;
          provider: string | null;
          status: string;
          cost: number;
          notes: string | null;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['treatments']['Row'], 'created_at'>;
        Update: Partial<Database['public']['Tables']['treatments']['Insert']>;
      };
      payments: {
        Row: {
          id: string;
          clinic_id: string;
          patient_id: string;
          date: string;
          amount: number;
          method: string | null;
          treatment_id: string | null;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['payments']['Row'], 'created_at'>;
        Update: Partial<Database['public']['Tables']['payments']['Insert']>;
      };
      outreach: {
        Row: {
          id: string;
          clinic_id: string;
          patient_id: string;
          kind: string;
          channel: string;
          status: string;
          message: string;
          related_treatment_id: string | null;
          created_at: string;
          sent_at: string | null;
          responded_at: string | null;
        };
        Insert: Omit<Database['public']['Tables']['outreach']['Row'], 'created_at'>;
        Update: Partial<Database['public']['Tables']['outreach']['Insert']>;
      };
    };
  };
}
