import type { Business, Candidate, Job } from './types';

export const DEMO_BUSINESS: Business = {
  id: 'biz-1',
  name: 'בית קפה לינה',
  type: 'cafe',
  address: 'שדרות רוטשילד 55, תל אביב',
  location: { lat: 32.0628, lng: 34.7730 },
  operatorName: 'לוסיה',
  staffingState: 'has-gaps',
};

export const DEMO_JOB: Job = {
  id: 'job-1',
  businessId: 'biz-1',
  role: 'barista',
  locationAddress: 'שדרות רוטשילד 55, תל אביב',
  location: { lat: 32.0628, lng: 34.7730 },
  shifts: ['morning', 'evening'],
  startDate: '2026-07-01',
  requirements: 'ניסיון בהכנת קפה, יחסי אנוש טובים',
  wageNis: 55,
  filters: { roles: ['barista'], maxDistanceKm: 10 },
  weights: {
    availability: 0.30, distance: 0.25, roleExperience: 0.20,
    skills: 0.10, compensation: 0.10, recency: 0.05,
  },
  mustHaves: [],
  flow: 'flow2',
  status: 'active',
  createdAt: '2026-06-18',
};

const C: Record<string, string> = {
  c0: 'oklch(0.63 0.18 38)',
  c1: 'oklch(0.55 0.14 160)',
  c2: 'oklch(0.52 0.17 295)',
  c3: 'oklch(0.60 0.15 52)',
  c4: 'oklch(0.54 0.14 22)',
  c5: 'oklch(0.50 0.16 330)',
  c6: 'oklch(0.58 0.17 200)',
  c7: 'oklch(0.56 0.15 80)',
  c8: 'oklch(0.53 0.16 260)',
  c9: 'oklch(0.61 0.14 140)',
};

export const SEED_CANDIDATES: Candidate[] = [
  {
    id: 'c-1', businessId: 'biz-1',
    name: 'נועה לוי', initials: 'נל', avatarColor: C.c0,
    neighborhood: 'פלורנטין', location: { lat: 32.0569, lng: 34.7685 },
    hasCar: false, willingRangeKm: 5,
    availability: { days: ['sun','mon','tue','wed','thu'], shifts: ['evening'], hoursPerWeek: 30, earliestStart: '2026-07-01', immediate: false },
    roles: ['barista'], experience: { totalYears: 2, roles: ['barista'], venueTypes: ['cafe'], notableWorkplaces: ['אספרסו בר תל אביב'] },
    skills: ['espresso', 'latte-art'], languages: ['he','en'],
    hasWorkPermit: true, age: 24, expectedWageNis: 52,
    signals: { applicationCount: 3, priorHires: 1, responseSpeedHours: 2, lastActiveDaysAgo: 1 },
    consentSource: 'apply-form', addedAt: '2026-06-17',
  },
  {
    id: 'c-2', businessId: 'biz-1',
    name: 'איתי כהן', initials: 'אכ', avatarColor: C.c1,
    neighborhood: 'רמת אביב', location: { lat: 32.1076, lng: 34.8012 },
    hasCar: true, willingRangeKm: 12,
    availability: { days: ['sun','mon','tue','wed','thu'], shifts: ['morning'], hoursPerWeek: 40, earliestStart: '2026-07-01', immediate: false },
    roles: ['barista','bartender'], experience: { totalYears: 3, roles: ['barista','bartender'], venueTypes: ['cafe','bar'], notableWorkplaces: ['הבר שדרות'] },
    skills: ['espresso','cocktails'], languages: ['he','en'],
    hasWorkPermit: true, age: 27, expectedWageNis: 58,
    signals: { applicationCount: 5, priorHires: 2, responseSpeedHours: 4, lastActiveDaysAgo: 3 },
    consentSource: 'csv-import', addedAt: '2026-06-15',
  },
  {
    id: 'c-3', businessId: 'biz-1',
    name: 'דריה מיכאלוב', initials: 'דמ', avatarColor: C.c2,
    neighborhood: 'נווה צדק', location: { lat: 32.0543, lng: 34.7637 },
    hasCar: false, willingRangeKm: 3,
    availability: { days: ['sun','mon','tue','wed','thu','fri'], shifts: ['morning','afternoon','evening'], hoursPerWeek: 35, earliestStart: '2026-06-20', immediate: true },
    roles: ['barista','server'], experience: { totalYears: 1, roles: ['barista','server'], venueTypes: ['cafe'], notableWorkplaces: [] },
    skills: ['espresso'], languages: ['he','ru'],
    hasWorkPermit: true, age: 22, expectedWageNis: 48,
    signals: { applicationCount: 2, priorHires: 0, responseSpeedHours: 1, lastActiveDaysAgo: 0 },
    consentSource: 'apply-form', addedAt: '2026-06-18',
  },
  {
    id: 'c-4', businessId: 'biz-1',
    name: 'יוסף אבוטבול', initials: 'יא', avatarColor: C.c3,
    neighborhood: 'בת ים', location: { lat: 32.0229, lng: 34.7514 },
    hasCar: true, willingRangeKm: 15,
    availability: { days: ['sun','mon','tue','wed','thu','fri'], shifts: ['evening','night'], hoursPerWeek: 45, earliestStart: '2026-07-15', immediate: false },
    roles: ['bartender','barista'], experience: { totalYears: 4, roles: ['bartender','barista'], venueTypes: ['bar','cafe'], notableWorkplaces: ['הברמן רמת גן','קפה יחידה'] },
    skills: ['cocktails','espresso','pos'], languages: ['he','ar'],
    hasWorkPermit: true, age: 31, expectedWageNis: 62,
    signals: { applicationCount: 8, priorHires: 3, responseSpeedHours: 6, lastActiveDaysAgo: 2 },
    consentSource: 'csv-import', addedAt: '2026-06-14',
  },
  {
    id: 'c-5', businessId: 'biz-1',
    name: 'שיר בן דוד', initials: 'שב', avatarColor: C.c4,
    neighborhood: 'גבעתיים', location: { lat: 32.0697, lng: 34.8095 },
    hasCar: false, willingRangeKm: 6,
    availability: { days: ['mon','tue','wed','thu','fri'], shifts: ['afternoon','evening'], hoursPerWeek: 20, earliestStart: '2026-07-01', immediate: false },
    roles: ['server','cashier'], experience: { totalYears: 1, roles: ['server'], venueTypes: ['restaurant'], notableWorkplaces: [] },
    skills: ['pos'], languages: ['he'],
    hasWorkPermit: true, age: 19, expectedWageNis: 45,
    signals: { applicationCount: 1, priorHires: 0, responseSpeedHours: 12, lastActiveDaysAgo: 5 },
    consentSource: 'apply-form', addedAt: '2026-06-13',
  },
  {
    id: 'c-6', businessId: 'biz-1',
    name: 'מאיה גולן', initials: 'מג', avatarColor: C.c5,
    neighborhood: 'לב תל אביב', location: { lat: 32.0640, lng: 34.7729 },
    hasCar: false, willingRangeKm: 4,
    availability: { days: ['sun','mon','tue','wed','thu','fri','sat'], shifts: ['morning','afternoon'], hoursPerWeek: 40, earliestStart: '2026-06-20', immediate: true },
    roles: ['barista'], experience: { totalYears: 1, roles: ['barista'], venueTypes: ['cafe'], notableWorkplaces: ['בית קפה שכונתי'] },
    skills: ['espresso'], languages: ['he','en'],
    hasWorkPermit: true, age: 25, expectedWageNis: 50,
    signals: { applicationCount: 2, priorHires: 0, responseSpeedHours: 1, lastActiveDaysAgo: 0 },
    consentSource: 'apply-form', addedAt: '2026-06-18',
  },
  {
    id: 'c-7', businessId: 'biz-1',
    name: 'אמיר חסן', initials: 'אח', avatarColor: C.c6,
    neighborhood: 'יפו', location: { lat: 32.0486, lng: 34.7527 },
    hasCar: true, willingRangeKm: 10,
    availability: { days: ['sun','mon','tue','wed','thu'], shifts: ['morning','afternoon','evening'], hoursPerWeek: 40, earliestStart: '2026-07-01', immediate: false },
    roles: ['cook','line-cook'], experience: { totalYears: 5, roles: ['cook','line-cook'], venueTypes: ['restaurant','cafe'], notableWorkplaces: ['מסעדת הים','פיצה רומא'] },
    skills: ['food-prep','food-hygiene-cert'], languages: ['he','ar'],
    hasWorkPermit: true, age: 28, expectedWageNis: 60,
    signals: { applicationCount: 4, priorHires: 2, responseSpeedHours: 3, lastActiveDaysAgo: 1 },
    consentSource: 'csv-import', addedAt: '2026-06-16',
  },
  {
    id: 'c-8', businessId: 'biz-1',
    name: 'רינת שלום', initials: 'רש', avatarColor: C.c7,
    neighborhood: 'כפר סבא', location: { lat: 32.1800, lng: 34.9070 },
    hasCar: true, willingRangeKm: 20,
    availability: { days: ['sun','mon','tue','wed','thu'], shifts: ['morning'], hoursPerWeek: 30, earliestStart: '2026-07-15', immediate: false },
    roles: ['server','host'], experience: { totalYears: 3, roles: ['server','host'], venueTypes: ['restaurant','cafe'], notableWorkplaces: ['מסעדת גנים'] },
    skills: ['pos'], languages: ['he','en'],
    hasWorkPermit: true, age: 26, expectedWageNis: 55,
    signals: { applicationCount: 3, priorHires: 1, responseSpeedHours: 8, lastActiveDaysAgo: 4 },
    consentSource: 'csv-import', addedAt: '2026-06-12',
  },
  {
    id: 'c-9', businessId: 'biz-1',
    name: 'ליאור שפירא', initials: 'לש', avatarColor: C.c8,
    neighborhood: 'רמת גן', location: { lat: 32.0804, lng: 34.8249 },
    hasCar: true, willingRangeKm: 8,
    availability: { days: ['sun','mon','tue','wed','thu','fri'], shifts: ['morning','afternoon','evening','night'], hoursPerWeek: 50, earliestStart: '2026-06-25', immediate: true },
    roles: ['bartender','barista','shift-manager'], experience: { totalYears: 6, roles: ['bartender','barista','shift-manager'], venueTypes: ['bar','cafe','hotel'], notableWorkplaces: ['ברם','מלון רמת גן'] },
    skills: ['espresso','cocktails','pos','food-hygiene-cert'], languages: ['he','en','ru'],
    hasWorkPermit: true, age: 32, expectedWageNis: 70,
    signals: { applicationCount: 10, priorHires: 4, responseSpeedHours: 2, lastActiveDaysAgo: 0 },
    consentSource: 'apply-form', addedAt: '2026-06-18',
  },
  {
    id: 'c-10', businessId: 'biz-1',
    name: 'פאטמה עלי', initials: 'פע', avatarColor: C.c9,
    neighborhood: 'לוד', location: { lat: 31.9517, lng: 34.8956 },
    hasCar: true, willingRangeKm: 20,
    availability: { days: ['sun','mon','tue','wed','thu'], shifts: ['morning','afternoon'], hoursPerWeek: 35, earliestStart: '2026-07-01', immediate: false },
    roles: ['cook','dishwasher'], experience: { totalYears: 2, roles: ['cook','dishwasher'], venueTypes: ['restaurant','fast-food'], notableWorkplaces: [] },
    skills: ['food-prep','food-hygiene-cert'], languages: ['he','ar'],
    hasWorkPermit: true, age: 23, expectedWageNis: 48,
    signals: { applicationCount: 2, priorHires: 0, responseSpeedHours: 5, lastActiveDaysAgo: 2 },
    consentSource: 'apply-form', addedAt: '2026-06-16',
  },
  {
    id: 'c-11', businessId: 'biz-1',
    name: 'אנסטסיה פטרוב', initials: 'אפ', avatarColor: C.c0,
    neighborhood: 'הרצליה', location: { lat: 32.1643, lng: 34.8441 },
    hasCar: true, willingRangeKm: 15,
    availability: { days: ['sun','mon','tue','wed','thu'], shifts: ['morning','afternoon'], hoursPerWeek: 30, earliestStart: '2026-07-01', immediate: false },
    roles: ['barista','cashier'], experience: { totalYears: 2, roles: ['barista'], venueTypes: ['cafe'], notableWorkplaces: ['קפה גולדה'] },
    skills: ['espresso','pos'], languages: ['he','ru','en'],
    hasWorkPermit: true, age: 25, expectedWageNis: 52,
    signals: { applicationCount: 3, priorHires: 1, responseSpeedHours: 3, lastActiveDaysAgo: 1 },
    consentSource: 'csv-import', addedAt: '2026-06-17',
  },
  {
    id: 'c-12', businessId: 'biz-1',
    name: 'כרמל דניאל', initials: 'כד', avatarColor: C.c1,
    neighborhood: 'שכונת התקווה', location: { lat: 32.0440, lng: 34.7942 },
    hasCar: false, willingRangeKm: 5,
    availability: { days: ['sun','mon','tue','wed','thu','fri'], shifts: ['evening','night','weekend'], hoursPerWeek: 25, earliestStart: '2026-06-20', immediate: true },
    roles: ['server','barista'], experience: { totalYears: 1, roles: ['server'], venueTypes: ['cafe','bar'], notableWorkplaces: [] },
    skills: ['pos'], languages: ['he'],
    hasWorkPermit: true, age: 20, expectedWageNis: 47,
    signals: { applicationCount: 1, priorHires: 0, responseSpeedHours: 2, lastActiveDaysAgo: 0 },
    consentSource: 'apply-form', addedAt: '2026-06-18',
  },
  {
    id: 'c-13', businessId: 'biz-1',
    name: 'טל מורנו', initials: 'טמ', avatarColor: C.c2,
    neighborhood: 'הצפון הישן', location: { lat: 32.0860, lng: 34.7790 },
    hasCar: false, willingRangeKm: 4,
    availability: { days: ['sun','mon','tue','wed','thu'], shifts: ['morning','afternoon'], hoursPerWeek: 40, earliestStart: '2026-07-01', immediate: false },
    roles: ['barista'], experience: { totalYears: 3, roles: ['barista'], venueTypes: ['cafe'], notableWorkplaces: ['קפה גנים','נורד'] },
    skills: ['espresso','latte-art','food-hygiene-cert'], languages: ['he','en'],
    hasWorkPermit: true, age: 29, expectedWageNis: 57,
    signals: { applicationCount: 6, priorHires: 2, responseSpeedHours: 2, lastActiveDaysAgo: 1 },
    consentSource: 'csv-import', addedAt: '2026-06-15',
  },
  {
    id: 'c-14', businessId: 'biz-1',
    name: 'ג׳וני מסרוב', initials: 'גמ', avatarColor: C.c3,
    neighborhood: 'בני ברק', location: { lat: 32.0831, lng: 34.8337 },
    hasCar: true, willingRangeKm: 10,
    availability: { days: ['sun','mon','tue','wed','thu'], shifts: ['morning','afternoon'], hoursPerWeek: 40, earliestStart: '2026-07-01', immediate: false },
    roles: ['cook','line-cook'], experience: { totalYears: 7, roles: ['cook','line-cook'], venueTypes: ['restaurant','hotel','catering'], notableWorkplaces: ['מסעדת ים תיכון','הולידיי אין'] },
    skills: ['food-prep','food-hygiene-cert','kashrut'], languages: ['he','ru'],
    hasWorkPermit: true, age: 35, expectedWageNis: 68,
    signals: { applicationCount: 5, priorHires: 3, responseSpeedHours: 4, lastActiveDaysAgo: 2 },
    consentSource: 'csv-import', addedAt: '2026-06-14',
  },
  {
    id: 'c-15', businessId: 'biz-1',
    name: 'עמית צור', initials: 'עצ', avatarColor: C.c4,
    neighborhood: 'גבעת שמואל', location: { lat: 32.0730, lng: 34.8432 },
    hasCar: false, willingRangeKm: 6,
    availability: { days: ['sun','mon','wed','thu'], shifts: ['afternoon','evening'], hoursPerWeek: 20, earliestStart: '2026-07-01', immediate: false },
    roles: ['barista','cashier'], experience: { totalYears: 1, roles: ['barista'], venueTypes: ['cafe'], notableWorkplaces: ['קפה האוניברסיטה'] },
    skills: ['espresso'], languages: ['he','en'],
    hasWorkPermit: true, age: 21, expectedWageNis: 45,
    signals: { applicationCount: 2, priorHires: 0, responseSpeedHours: 8, lastActiveDaysAgo: 7 },
    consentSource: 'apply-form', addedAt: '2026-06-11',
  },
  {
    id: 'c-16', businessId: 'biz-1',
    name: 'שחר פרידמן', initials: 'שפ', avatarColor: C.c5,
    neighborhood: 'תל אביב מרכז', location: { lat: 32.0715, lng: 34.7808 },
    hasCar: false, willingRangeKm: 4,
    availability: { days: ['sun','mon','tue','wed','thu','fri'], shifts: ['morning','evening'], hoursPerWeek: 35, earliestStart: '2026-06-25', immediate: true },
    roles: ['barista'], experience: { totalYears: 2, roles: ['barista'], venueTypes: ['cafe'], notableWorkplaces: ['ג׳ו בר'] },
    skills: ['espresso','latte-art'], languages: ['he','en'],
    hasWorkPermit: true, age: 26, expectedWageNis: 53,
    signals: { applicationCount: 4, priorHires: 1, responseSpeedHours: 1, lastActiveDaysAgo: 0 },
    consentSource: 'apply-form', addedAt: '2026-06-18',
  },
  {
    id: 'c-17', businessId: 'biz-1',
    name: 'ורד אלחרר', initials: 'וא', avatarColor: C.c6,
    neighborhood: 'פתח תקווה', location: { lat: 32.0840, lng: 34.8878 },
    hasCar: true, willingRangeKm: 12,
    availability: { days: ['sun','mon','tue','wed','thu'], shifts: ['morning','afternoon'], hoursPerWeek: 40, earliestStart: '2026-07-01', immediate: false },
    roles: ['server','host'], experience: { totalYears: 4, roles: ['server','host'], venueTypes: ['restaurant','cafe'], notableWorkplaces: ['מסעדת הפרג'] },
    skills: ['pos','food-hygiene-cert'], languages: ['he','ar','en'],
    hasWorkPermit: true, age: 30, expectedWageNis: 56,
    signals: { applicationCount: 5, priorHires: 2, responseSpeedHours: 5, lastActiveDaysAgo: 3 },
    consentSource: 'csv-import', addedAt: '2026-06-13',
  },
  {
    id: 'c-18', businessId: 'biz-1',
    name: 'בן אלון', initials: 'בא', avatarColor: C.c7,
    neighborhood: 'כרם התימנים', location: { lat: 32.0587, lng: 34.7701 },
    hasCar: false, willingRangeKm: 3,
    availability: { days: ['tue','wed','thu','fri','sat'], shifts: ['evening','night','weekend'], hoursPerWeek: 30, earliestStart: '2026-07-01', immediate: false },
    roles: ['bartender','server'], experience: { totalYears: 3, roles: ['bartender','server'], venueTypes: ['bar'], notableWorkplaces: ['הלוי בר'] },
    skills: ['cocktails','pos'], languages: ['he','en'],
    hasWorkPermit: true, age: 23, expectedWageNis: 56,
    signals: { applicationCount: 4, priorHires: 1, responseSpeedHours: 3, lastActiveDaysAgo: 2 },
    consentSource: 'apply-form', addedAt: '2026-06-16',
  },
  {
    id: 'c-19', businessId: 'biz-1',
    name: 'ניסים דהן', initials: 'נד', avatarColor: C.c8,
    neighborhood: 'ראשון לציון', location: { lat: 31.9730, lng: 34.7891 },
    hasCar: true, willingRangeKm: 18,
    availability: { days: ['sun','mon','tue','wed','thu'], shifts: ['morning','afternoon'], hoursPerWeek: 45, earliestStart: '2026-07-01', immediate: false },
    roles: ['dishwasher','cook'], experience: { totalYears: 0, roles: ['dishwasher'], venueTypes: ['restaurant'], notableWorkplaces: [] },
    skills: ['food-hygiene-cert'], languages: ['he'],
    hasWorkPermit: true, age: 18, expectedWageNis: 40,
    signals: { applicationCount: 1, priorHires: 0, responseSpeedHours: 24, lastActiveDaysAgo: 10 },
    consentSource: 'apply-form', addedAt: '2026-06-08',
  },
  {
    id: 'c-20', businessId: 'biz-1',
    name: 'מרינה ברגמן', initials: 'מב', avatarColor: C.c9,
    neighborhood: 'הצפון הרחוק', location: { lat: 32.1200, lng: 34.8210 },
    hasCar: true, willingRangeKm: 10,
    availability: { days: ['sun','mon','tue','wed','thu','fri'], shifts: ['morning'], hoursPerWeek: 30, earliestStart: '2026-07-15', immediate: false },
    roles: ['barista','cashier'], experience: { totalYears: 4, roles: ['barista','cashier'], venueTypes: ['cafe','hotel'], notableWorkplaces: ['הילטון תל אביב','קפה גרג'] },
    skills: ['espresso','pos','food-hygiene-cert'], languages: ['he','ru','en'],
    hasWorkPermit: true, age: 34, expectedWageNis: 60,
    signals: { applicationCount: 6, priorHires: 3, responseSpeedHours: 6, lastActiveDaysAgo: 4 },
    consentSource: 'csv-import', addedAt: '2026-06-10',
  },
];
